---
# ejemplo para clientes con su propio namespace
kind: Namespace
apiVersion: v1
metadata:
  name: suin-dolcezza
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: suinsit-licence
  namespace: suin-dolcezza
data:
  customer_uid: "4afa94b6-2ecc-4702-af71-38f65fb307cc"
  customer_name: "rotadis"
  customer_code: "2023/00005128"
  customer_owner: "rotadis"
  customer_repository: "rotadis-source" 
  customer_label: "Rotadis Niño S.L."
  suinsit_branch: "2.0.0"
  suinsit_version: "2.0.0"
  suinsit_product: "ecomm"
  atlas_proyect: "SC/2023/0000000018"
---
# secret azure-key
apiVersion: v1
kind: Secret
metadata:
  name: rabbit-user
  namespace: suin-dolcezza
type: Opaque
stringData:
  username: suinsit
  password: VpMV62YWXLd97BZ
---
apiVersion: v1 
kind: ConfigMap 
metadata:
  name: max-conns
  namespace: suin-dolcezza
data:
  max_conns.sql: "ALTER SYSTEM SET max_connections = 1000;"
---
# secret base de datos y otras conexiones
apiVersion: v1
kind: Secret
metadata:
  name: bbdd
  namespace: suin-dolcezza
type: Opaque
stringData:
  username: suinsit
  password: MWYyZDFlMmU2N2Rm
---
# storage to database
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-pgsql
  namespace: suin-dolcezza
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    # csi-cinder-classic hdd classic csi-cinder-high-speed ssd disc
    requests:
      storage: 10Gi
  storageClassName: csi-cinder-high-speed
---
# storage to suinsit
---
    kind: PersistentVolumeClaim
    apiVersion: v1
    metadata:
      name: pvc-suinsit
      namespace: suin-dolcezza
    spec:
      storageClassName: "nfs"
      accessModes:
        - ReadWriteMany
      resources:
        requests:
          storage: 20Gi
---
# deployment base de datos dedicada
apiVersion: apps/v1 
kind: Deployment
metadata:
  name: postgres
  namespace: suin-dolcezza
spec:
  selector:
    matchLabels:
      app: postgres
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - image: postgres:15.4-alpine3.18
        name: postgres
        resources:
          requests:
            memory: "1024Mi"
            cpu: "0.5"
          limits:
            memory: "2024Mi"
            cpu: "1.5"
        env:
          # Use secret in real usage
        # Use secret in real usage
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
               name: bbdd
               key: password
         # value: MWYyZDFlMmU2N2Rm
        - name: POSTGRES_MULTIPLE_DATABASES
          value: flowable,suinsit,axesor
        #- name: POSTGRES_DB
         # value: suinsit
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
               name: bbdd
               key: username
        - name: PGDATA
          value: /var/lib/postgresql/data
        ports:
        - containerPort: 5432
          #hostPort: 5432
          #name: postgres
        volumeMounts:
        - name: postgres-persistent-storage
          mountPath: /var/lib/postgresql/data
          subPath: postgres 
        - name: max-conns
          mountPath: /docker-entrypoint-initdb.d
      volumes:
      - name: max-conns
        configMap:
            name: max-conns    
      - name: postgres-persistent-storage
        persistentVolumeClaim:
          claimName: pvc-pgsql
      
      
---
# -- suinsit - sidecar 
apiVersion: apps/v1 
kind: Deployment
metadata:
  name: sidecar
  namespace: suin-dolcezza
spec:
  selector:
    matchLabels:
      app: sidecar
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: sidecar
    spec:
      containers:
# image to suinsit-app
      - image: 2w1x0a76.gra7.container-registry.ovh.net/suinsit-core/suinsit/sidecar:1.1.19
        name: sidecar
        resources:
          requests:
            memory: "256Mi"
            cpu: "50m"
          limits:
            memory: "2048Mi"
            cpu: "750m"
        env:
          # Use secret in real usage
        - name: JAVA_OPTIONS
          value: -Duser.language=es -Duser.country=ES -Duser.timezone="Europe/Madrid" -server -Xms256m -Xmx2048m -XX:+UseG512mC -XX:+UseStringDeduplication -XX:MaxMetaspaceSize=512m -XX:+ScavengeBeforeFullGC  
        - name: SUINSIT_BBDD
          value: suinsit
        - name: SUINSIT_BBDD_DRIVER
          value: org.postgresql.Driver
        - name: SUINSIT_BBDD_PASSWORD
          valueFrom:
            secretKeyRef:
               name: bbdd
               key: password
        - name: SUINSIT_BBDD_URL
          value: jdbc:postgresql://postgres-tcp:5432/suinsit
        - name: SUINSIT_BBDD_USERNAME
          valueFrom:
            secretKeyRef:
               name: bbdd
               key: username
        - name: AMQ_USER
          valueFrom:
            secretKeyRef:
               name: rabbit-user
               key: username
        - name: AMQ_PASSWORD
          valueFrom:
            secretKeyRef:
               name: rabbit-user
               key: password
        - name: SUINSIT_VERSION
          valueFrom:
            configMapKeyRef:
              name: suinsit-licence         
              key: suinsit_branch 
        - name: AMQ_HOST
          value: rabbitmq.suinsit-systems.svc.cluster.local      
        - name: AMQ_PORT
          value: "5672"                    
        - name: SUINSIT_LOGS
          value: /opt/suinsit/logs         
        - name: ROOT_LOG
          value: ERROR
        - name: TECHNICAL_LOG
          value: DEBUG       
        - name: SUINSIT_CUSTOMER_NAME
          valueFrom:
            configMapKeyRef:
              name: suinsit-licence         
              key: customer_name
        - name: SUINSIT_CUSTOMER_LABEL
          valueFrom:
            configMapKeyRef:
              name: suinsit-licence         
              key: customer_label      
        - name: SUINSIT_CUSTOMER_UID
          valueFrom:
            configMapKeyRef:
              name: suinsit-licence         
              key: customer_uid
        - name: SUINSIT_CUSTOMER_REPOSITORY
          valueFrom:
            configMapKeyRef:
              name: suinsit-licence         
              key: customer_repository
        - name: SUINSIT_ENVIROMENT
          value: PRO
        - name: SUINSIT_APPLICATION
          value: office    
        - name: SUINSIT_EXECUTION
          value: cloud
        - name: SUINSIT_ROOT
          value: /opt/suinsit/  
        - name: SUINSIT_HOME
          value: /opt/suinsit/application
        - name: SUINSIT_PRODUCT
          valueFrom:
            configMapKeyRef:
              name: suinsit-licence         
              key: suinsit_product  
        - name: BBDD_HOST
          value: postgres-tcp   
        - name: BBDD_PORT
          value: "5432"
        - name: BBDD_NAME
          value: suinsit  
        volumeMounts:
        - name: suinsit-persistent-storage
          mountPath: /opt/suinsit
          subPath: suinsit
      imagePullSecrets:
      - name: regcred
      volumes:
      - name: suinsit-persistent-storage
        persistentVolumeClaim:
          claimName: pvc-suinsit           

---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: suin-dolcezza
spec:
  ports:
  - port: 5432
  selector:
    app: postgres
  clusterIP: None
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-tcp
  namespace: suin-dolcezza
spec:
  type: NodePort
  selector:
    app: postgres
  ports:
  - protocol: TCP
    port: 5432
    targetPort: 5432        
