[ {
  "cloneOther" : [ 71 ],
  "importData" : [ 71, 72 ],
  "useData" : [ 71, 72 ],
  "useJson" : [ 72 ],
  "props" : { },
  "selected" : false,
  "idxarchitect" : 71,
  "delete" : false,
  "active" : true,
  "clxmlconfig" : null,
  "imagen" : "img/programming/zklogo2_tn.png",
  "icono" : null,
  "txhandlerclass" : "io.artfacto.core.factory.SimpleFactoryArchitect",
  "txbasepackage" : "io.suinsit.architecture.nczkee",
  "fxalta" : null,
  "dsdescription" : "Arquitectura de aplicaciones no-code bajo el framework zkoss y discovery",
  "btactive" : null,
  "txname" : "Web Application No Code",
  "mddmentity" : [ ],
  "mddmproject" : [ ],
  "path" : null,
  "cocode" : null
}
,{
  "cloneOther" : [ 71 ],
  "importData" : [ 71, 72 ],
  "useData" : [ 71, 72 ],
  "useJson" : [ 72 ],
  "props" : { },
  "selected" : false,
  "idxarchitect" : 71,
  "delete" : false,
  "active" : true,
  "clxmlconfig" : null,
  "imagen" : "img/programming/zklogo2_tn.png",
  "icono" : null,
  "txhandlerclass" : "io.artfacto.core.factory.SimpleFactoryArchitect",
  "txbasepackage" : "io.suinsit.architecture.nczkee",
  "fxalta" : null,
  "dsdescription" : "Aplicaciones web basadas en framework Zkoss 9.5 version EE",
  "btactive" : null,
  "txname" : "Web Application Open-LowCode",
  "mddmentity" : [ ],
  "mddmproject" : [ ],
  "path" : null,
  "cocode" : null
}
, {
  "cloneOther" : [ ],
  "importData" : [ ],
  "useData" : [ ],
  "useJson" : [ ],
  "props" : { },
  "selected" : false,
  "idxarchitect" : 75,
  "delete" : false,
  "active" : false,
  "clxmlconfig" : null,
  "imagen" : "img/programming/reactjs.png",
  "icono" : null,
  "txhandlerclass" : "io.artfacto.core.factory.SimpleFactoryArchitect",
  "txbasepackage" : "io.suinsit.architecture.datastream",
  "fxalta" : null,
  "dsdescription" : "Arquitectura aplicaciones web basadas en reactjs Pending...",
  "btactive" : null,
  "txname" : "WEB APPLICATION REACTJS 16.3.1",
  "mddmentity" : [ ],
  "mddmproject" : [ ],
  "path" : null,
  "cocode" : null
}, {
  "cloneOther" : [ ],
  "importData" : [ ],
  "useData" : [ ],
  "useJson" : [ ],
  "props" : { },
  "selected" : false,
  "idxarchitect" : 75,
  "delete" : false,
  "active" : false,
  "clxmlconfig" : null,
  "imagen" : "img/programming/angular.png",
  "icono" : null,
  "txhandlerclass" : "io.artfacto.core.factory.SimpleFactoryArchitect",
  "txbasepackage" : "io.suinsit.architecture.datastream",
  "fxalta" : null,
  "dsdescription" : "Arquitectura aplicaciones web basadas en angularjs Pending...",
  "btactive" : null,
  "txname" : "WEB APPLICATION ANGULARJS 10",
  "mddmentity" : [ ],
  "mddmproject" : [ ],
  "path" : null,
  "cocode" : null
}, {
  "cloneOther" : [ ],
  "importData" : [ ],
  "useData" : [ ],
  "useJson" : [ ],
  "props" : { },
  "selected" : false,
  "idxarchitect" : 75,
  "delete" : false,
  "active" : false,
  "clxmlconfig" : null,
  "imagen" : "img/programming/vuejs.png",
  "icono" : null,
  "txhandlerclass" : "io.artfacto.core.factory.SimpleFactoryArchitect",
  "txbasepackage" : "io.suinsit.architecture.datastream",
  "fxalta" : null,
  "dsdescription" : "Arquitectura aplicaciones web basadas en vuejs Pending...",
  "btactive" : null,
  "txname" : "WEB APPLICATION VUEJS 2",
  "mddmentity" : [ ],
  "mddmproject" : [ ],
  "path" : null,
  "cocode" : null
}, {
  "cloneOther" : [ 72 ],
  "importData" : [ 71, 72 ],
  "useData" : [ 71, 72 ],
  "useJson" : [ 72 ],
  "props" : { },
  "selected" : false,
  "idxarchitect" : 72,
  "delete" : false,
  "active" : true,
  "clxmlconfig" : null,
  "imagen" : "img/programming/vertx-sm.png",
  "icono" : null,
  "txhandlerclass" : "io.artfacto.core.factory.SimpleFactoryArchitect",
  "txbasepackage" : "io.suinsit.architecture.micros",
  "fxalta" : null,
  "dsdescription" : "Arquitectura Java de microservicios implementada con el toolkit de vertx 3.9.4",
  "btactive" : null,
  "txname" : "Microservices vertx",
  "mddmentity" : [ ],
  "mddmproject" : [ ],
  "path" : null,
  "cocode" : null
}
, {
  "cloneOther" : [ 72 ],
  "importData" : [ 71, 72 ],
  "useData" : [ 71, 72 ],
  "useJson" : [ 72 ],
  "props" : { },
  "selected" : false,
  "idxarchitect" : 72,
  "delete" : false,
  "active" : true,
  "clxmlconfig" : null,
  "imagen" : "img/programming/quarkus.jpeg",
  "icono" : null,
  "txhandlerclass" : "io.artfacto.core.factory.SimpleFactoryArchitect",
  "txbasepackage" : "io.suinsit.architecture.micros",
  "fxalta" : null,
  "dsdescription" : "Arquitectura Java de microservicios implementada con el framework Quarkus 1.8.3",
  "btactive" : null,
  "txname" : "Quarkus Framework",
  "mddmentity" : [ ],
  "mddmproject" : [ ],
  "path" : null,
  "cocode" : null
}
, {
  "cloneOther" : [ 72 ],
  "importData" : [ 71, 72 ],
  "useData" : [ 71, 72 ],
  "useJson" : [ 72 ],
  "props" : { },
  "selected" : false,
  "idxarchitect" : 72,
  "delete" : false,
  "active" : true,
  "clxmlconfig" : null,
  "imagen" : "img/programming/santander.png",
  "icono" : null,
  "txhandlerclass" : "io.artfacto.core.factory.SimpleFactoryArchitect",
  "txbasepackage" : "io.suinsit.architecture.micros",
  "fxalta" : null,
  "dsdescription" : "Arquitectura java de microservicios basada en el framework propio kyber y el toolkit vertx",
  "btactive" : null,
  "txname" : "Kyber Santander Consumer",
  "mddmentity" : [ ],
  "mddmproject" : [ ],
  "path" : null,
  "cocode" : null
}
, {
  "cloneOther" : [ 72 ],
  "importData" : [ 71, 72 ],
  "useData" : [ 71, 72 ],
  "useJson" : [ 72 ],
  "props" : { },
  "selected" : false,
  "idxarchitect" : 72,
  "delete" : false,
  "active" : true,
  "clxmlconfig" : null,
  "imagen" : "img/programming/springcloud.png",
  "icono" : null,
  "txhandlerclass" : "io.artfacto.core.factory.SimpleFactoryArchitect",
  "txbasepackage" : "io.suinsit.architecture.micros",
  "fxalta" : null,
  "dsdescription" : "Arquitectura Java de microservicios implementada con el framework EUPL enart y el framework Spring Boot",
  "btactive" : null,
  "txname" : "ENART Microservices Spring Cloud",
  "mddmentity" : [ ],
  "mddmproject" : [ ],
  "path" : null,
  "cocode" : null
}
, {
  "cloneOther" : [ 73 ],
  "importData" : [ 71, 72 ],
  "useData" : [ 71, 72 ],
  "useJson" : [ 72 ],
  "props" : { },
  "selected" : false,
  "idxarchitect" : 73,
  "delete" : false,
  "active" : false,
  "clxmlconfig" : null,
  "imagen" : "iconos/svg/049-data-storage.svg",
  "icono" : null,
  "txhandlerclass" : "io.artfacto.core.factory.SimpleFactoryArchitect",
  "txbasepackage" : "io.suinsit.architecture.datastream",
  "fxalta" : null,
  "dsdescription" : "Arquitectura de micros con kafka Pending...",
  "btactive" : null,
  "txname" : "Suinsit Cloud Data Stream",
  "mddmentity" : [ ],
  "mddmproject" : [ ],
  "path" : null,
  "cocode" : null
}, {
  "cloneOther" : [ ],
  "importData" : [ ],
  "useData" : [ ],
  "useJson" : [ ],
  "props" : { },
  "selected" : false,
  "idxarchitect" : 74,
  "delete" : false,
  "active" : false,
  "clxmlconfig" : null,
  "imagen" : "iconos/svg/040-diamond.svg",
  "icono" : null,
  "txhandlerclass" : "io.artfacto.core.factory.SimpleFactoryArchitect",
  "txbasepackage" : "io.suinsit.architecture.datastream",
  "fxalta" : null,
  "dsdescription" : "BPMN y orquestacion bajo el motor de camunda Pending...",
  "btactive" : null,
  "txname" : "Suinsit BPMN",
  "mddmentity" : [ ],
  "mddmproject" : [ ],
  "path" : null,
  "cocode" : null
}, {
  "cloneOther" : [ ],
  "importData" : [ ],
  "useData" : [ ],
  "useJson" : [ ],
  "props" : { },
  "selected" : false,
  "idxarchitect" : 76,
  "delete" : false,
  "active" : false,
  "clxmlconfig" : null,
  "imagen" : "iconos/svg/010-line-graphic.svg",
  "icono" : null,
  "txhandlerclass" : "io.artfacto.core.factory.SimpleFactoryArchitect",
  "txbasepackage" : "io.suinsit.architecture.datastream",
  "fxalta" : null,
  "dsdescription" : "Pending...",
  "btactive" : null,
  "txname" : "Suinsit Charts Reports",
  "mddmentity" : [ ],
  "mddmproject" : [ ],
  "path" : null,
  "cocode" : null
}, {
  "cloneOther" : [ ],
  "importData" : [ ],
  "useData" : [ ],
  "useJson" : [ ],
  "props" : { },
  "selected" : false,
  "idxarchitect" : 75,
  "delete" : false,
  "active" : false,
  "clxmlconfig" : null,
  "imagen" : "iconos/svg/025-cloud-storage.svg",
  "icono" : null,
  "txhandlerclass" : "io.artfacto.core.factory.SimpleFactoryArchitect",
  "txbasepackage" : "io.suinsit.architecture.datastream",
  "fxalta" : null,
  "dsdescription" : "IONIC 5 Pending...",
  "btactive" : null,
  "txname" : "Suinsit Movile App",
  "mddmentity" : [ ],
  "mddmproject" : [ ],
  "path" : null,
  "cocode" : null
} ]
