{
  "databases" : [ {
    "server" : null,
    "datasource" : null,
    "scripts" : [ ],
    "defecto" : true,
    "online" : true,
    "updateModel" : false,
    "updateData" : true,
    "createProject" : true,
    "serverFromProject" : false,
    "demo" : true,
    "id" : "2",
    "name" : "H2",
    "host" : null,
    "database" : null,
    "url" : "jdbc:h2:tcp://localhost:9095//opt/suinsit/database/projects/suinsit",
    "password" : "suinsit2021",
    "user" : "suinsit",
    "schema" : null,
    "driver" : "org.h2.Driver",
    "classDAO" : null,
    "classMetaModel" : "org.enartframework.schema.database.ddl.h2.datamodel.MetamodeloImpl",
    "classServer" : "org.enartframework.schema.database.ddl.h2.ServerImpl",
    "argsServer" : "-tcpPort| 9095|-tcpAllowOthers|-baseDir|$SUINSIT_HOME$/database/projects|-ifNotExists|-tcpDaemon",
    "serverhost" : null,
    "licence" : "FREE",
    "port" : 0,
    "fields" : [ ],
    "mfieldBean" : null,
    "msemanticBean" : { }
  }, {
    "server" : null,
    "datasource" : null,
    "scripts" : [ ],
    "defecto" : false,
    "online" : true,
    "updateModel" : false,
    "updateData" : true,
    "createProject" : true,
    "serverFromProject" : false,
    "demo" : false,
    "id" : "6",
    "name" : "PGSQL",
    "host" : null,
    "database" : "suinsit",
    "url" : "jdbc:postgresql://$SERVER_IP$:$SERVER_PORT$/$DATABASE$",
    "password" : "WUzKVFunwV1",
    "user" : "suinsit",
    "schema" : null,
    "driver" : "org.postgresql.Driver",
    "classDAO" : null,
    "classMetaModel" : "org.enartframework.schema.database.ddl.pgsql.datamodel.MetamodeloImpl",
    "classServer" : "org.enartframework.schema.database.ddl.h2.ServerImpl",
    "argsServer" : null,
    "serverhost" : "146.59.204.240",
    "licence" : "PERSONAL|NEXUM|PROFESIONAL|TEAM",
    "port" : 5432,
    "fields" : [ ],
    "mfieldBean" : null,
    "msemanticBean" : { }
  } ],
  "arquitecturas" : [ {
    "props" : null,
    "idxarchitect" : 1,
    "delete" : false,
    "active" : true,
    "clxmlconfig" : null,
    "imagen" : "iconos/svg/033-browsers.svg",
    "icono" : null,
    "txhandlerclass" : "org.enartframework.suinsit.factorys.SimpleFactoryArchitectImpl",
    "txbasepackage" : "io.suinsit.architecture.webzkee",
    "fxalta" : null,
    "dsdescription" : "Application No Code with framework Zkoss 9.5 version EE",
    "btactive" : false,
    "txname" : "Suinsit No Code",
    "path" : null,
    "cocode" : null,
    "licence" : "FREE|PERSONAL|PROFESIONAL|TEAM",
    "factory" : null,
    "cloneOther" : [ 71 ],
    "importData" : [ 71, 72 ],
    "useData" : [ 71, 72 ],
    "useJson" : [ 72 ]
  }, {
    "props" : null,
    "idxarchitect" : 71,
    "delete" : false,
    "active" : true,
    "clxmlconfig" : null,
    "imagen" : "iconos/svg/033-browsers.svg",
    "icono" : null,
    "txhandlerclass" : "org.enartframework.suinsit.factorys.SimpleFactoryArchitectImpl",
    "txbasepackage" : "com.suinsit.architecture.nczkee",
    "fxalta" : null,
    "dsdescription" : "arquitectura.nocode.zk.desc",
    "btactive" : false,
    "txname" : "Suinsit Web Application",
    "path" : null,
    "cocode" : null,
    "licence" : "FREE|PERSONAL|PROFESIONAL|TEAM",
    "factory" : null,
    "cloneOther" : [ 71 ],
    "importData" : [ 71, 72 ],
    "useData" : [ 71, 72 ],
    "useJson" : [ 72 ]
  }, {
    "props" : null,
    "idxarchitect" : 72,
    "delete" : false,
    "active" : true,
    "clxmlconfig" : null,
    "imagen" : "iconos/svg/030-web-page.svg",
    "icono" : null,
    "txhandlerclass" : "org.enartframework.suinsit.factorys.SimpleFactoryArchitectImpl",
    "txbasepackage" : "com.suinsit.architecture.micros",
    "fxalta" : null,
    "dsdescription" : "arquitectura.micros.desc",
    "btactive" : false,
    "txname" : "Suinsit Microservices",
    "path" : null,
    "cocode" : null,
    "licence" : "PROFESIONAL|TEAM",
    "factory" : null,
    "cloneOther" : [ 72 ],
    "importData" : [ 71, 72 ],
    "useData" : [ 71, 72 ],
    "useJson" : [ 72 ]
  }, {
    "props" : null,
    "idxarchitect" : 73,
    "delete" : false,
    "active" : false,
    "clxmlconfig" : null,
    "imagen" : "iconos/svg/049-data-storage.svg",
    "icono" : null,
    "txhandlerclass" : "org.enartframework.suinsit.factorys.SimpleFactoryArchitectImpl",
    "txbasepackage" : "com.suinsit.architecture.datastream",
    "fxalta" : null,
    "dsdescription" : "arquitectura.stream.model.desc",
    "btactive" : false,
    "txname" : "Suinsit Cloud Data Stream",
    "path" : null,
    "cocode" : null,
    "licence" : "PROFESIONAL|TEAM",
    "factory" : null,
    "cloneOther" : [ 73 ],
    "importData" : [ 71, 72 ],
    "useData" : [ 71, 72 ],
    "useJson" : [ 72 ]
  }, {
    "props" : null,
    "idxarchitect" : 74,
    "delete" : false,
    "active" : false,
    "clxmlconfig" : null,
    "imagen" : "iconos/svg/040-diamond.svg",
    "icono" : null,
    "txhandlerclass" : "org.enartframework.suinsit.factorys.SimpleFactoryArchitectImpl",
    "txbasepackage" : "com.suinsit.architecture.datastream",
    "fxalta" : null,
    "dsdescription" : "arquitectura.stream.model.desc",
    "btactive" : false,
    "txname" : "Suinsit BPMN",
    "path" : null,
    "cocode" : null,
    "licence" : "PROFESIONAL|TEAM",
    "factory" : null,
    "cloneOther" : [ ],
    "importData" : [ ],
    "useData" : [ ],
    "useJson" : [ ]
  }, {
    "props" : null,
    "idxarchitect" : 76,
    "delete" : false,
    "active" : false,
    "clxmlconfig" : null,
    "imagen" : "iconos/svg/010-line-graphic.svg",
    "icono" : null,
    "txhandlerclass" : "org.enartframework.suinsit.factorys.SimpleFactoryArchitectImpl",
    "txbasepackage" : "com.suinsit.architecture.datastream",
    "fxalta" : null,
    "dsdescription" : "arquitectura.stream.model.desc",
    "btactive" : false,
    "txname" : "Suinsit Charts Reports",
    "path" : null,
    "cocode" : null,
    "licence" : "PROFESIONAL|TEAM",
    "factory" : null,
    "cloneOther" : [ ],
    "importData" : [ ],
    "useData" : [ ],
    "useJson" : [ ]
  }, {
    "props" : null,
    "idxarchitect" : 75,
    "delete" : false,
    "active" : false,
    "clxmlconfig" : null,
    "imagen" : "iconos/svg/025-cloud-storage.svg",
    "icono" : null,
    "txhandlerclass" : "org.enartframework.suinsit.factorys.SimpleFactoryArchitectImpl",
    "txbasepackage" : "com.suinsit.architecture.datastream",
    "fxalta" : null,
    "dsdescription" : "arquitectura.stream.model.desc",
    "btactive" : false,
    "txname" : "Suinsit Movile App",
    "path" : null,
    "cocode" : null,
    "licence" : "PERSONAL|PROFESIONAL|TEAM",
    "factory" : null,
    "cloneOther" : [ ],
    "importData" : [ ],
    "useData" : [ ],
    "useJson" : [ ]
  } ]
}
