[ {
  "props" : null,
  "idxarchitect" : 1,
  "delete" : false,
  "active" : true,
  "clxmlconfig" : null,
  "imagen" : "iconos/svg/033-browsers.svg",
  "icono" : null,
  "txhandlerclass" : "org.enartframework.suinsit.factorys.SimpleFactoryArchitectImpl",
  "txbasepackage" : "io.suinsit.architecture.webzkee",
  "fxalta" : null,
  "dsdescription" : "Aplicación No Code, con tecnología java y frameworks zkoss y spring framewok",
  "btactive" : false,
  "txname" : "Suinsit No Code",
  "path" : null,
  "cocode" : null,
  "licence" : "FREE|PERSONAL|PROFESIONAL|TEAM",
  "factory" : null,
  "cloneOther" : [ 71 ],
  "importData" : [ 71, 72 ],
  "useData" : [ 71, 72 ],
  "useJson" : [ 72 ]
}, {
  "props" : null,
  "idxarchitect" : 71,
  "delete" : false,
  "active" : true,
  "clxmlconfig" : null,
  "imagen" : "img/programming/zklogo2_tn.png",
  "icono" : null,
  "txhandlerclass" : "org.enartframework.suinsit.factorys.SimpleFactoryArchitectImpl",
  "txbasepackage" : "com.suinsit.architecture.nczkee",
  "fxalta" : null,
  "dsdescription" : "Aplicación web clasica con tecnología java 15, zkoss, spring framework e hibernate.",
  "btactive" : false,
  "txname" : "Web Application Low Code",
  "path" : null,
  "cocode" : null,
  "licence" : "FREE|PERSONAL|PROFESIONAL|TEAM",
  "factory" : null,
  "cloneOther" : [ 71 ],
  "importData" : [ 71, 72 ],
  "useData" : [ 71, 72 ],
  "useJson" : [ 72 ]
},{
  "props" : null,
  "idxarchitect" : 77,
  "delete" : false,
  "active" : true,
  "clxmlconfig" : null,
  "imagen" : "img/programming/springcloud.png",
  "icono" : null,
  "txhandlerclass" : "org.enartframework.suinsit.factorys.SimpleFactoryArchitectImpl",
  "txbasepackage" : "com.suinsit.architecture.micros",
  "fxalta" : null,
  "dsdescription" : "Tecnología java de microservicios implementada con el framework de spring cloud y especificaciones OpenApi 3.0",
  "btactive" : false,
  "txname" : "Spring Cloud Microservices Low Code",
  "path" : null,
  "cocode" : null,
  "licence" : "FREE|PERSONAL|PROFESIONAL|TEAM",
  "factory" : null,
  "cloneOther" : [  ],
  "importData" : [ ],
  "useData" : [  ],
  "useJson" : [  ]
},{
  "props" : null,
  "idxarchitect" : 78,
  "delete" : false,
  "active" : true,
  "clxmlconfig" : null,
  "imagen" : "img/programming/vertx-sm.png",
  "icono" : null,
  "txhandlerclass" : "org.enartframework.suinsit.factorys.SimpleFactoryArchitectImpl",
  "txbasepackage" : "com.suinsit.architecture.micros",
  "fxalta" : null,
  "dsdescription" : "Tecnología java de microservicios implementada con el toolkit de vertx 4.0.0 y especificaciones OpenApi 3.0",
  "btactive" : false,
  "txname" : "Vertx Microservices Low Code",
  "path" : null,
  "cocode" : null,
  "licence" : "FREE|PERSONAL|PROFESIONAL|TEAM",
  "factory" : null,
  "cloneOther" : [  ],
  "importData" : [ ],
  "useData" : [  ],
  "useJson" : [  ]
}, {
  "props" : null,
  "idxarchitect" : 78,
  "delete" : false,
  "active" : true,
  "clxmlconfig" : null,
  "imagen" : "img/programming/reactjs.png",
  "icono" : null,
  "txhandlerclass" : "org.enartframework.suinsit.factorys.SimpleFactoryArchitectImpl",
  "txbasepackage" : "com.suinsit.architecture.micros",
  "fxalta" : null,
  "dsdescription" : "Aplicaciones web con tecnología ReactJs y backend con micro servicios java springboot ",
  "btactive" : false,
  "txname" : "ReactJs aplicación Low Code",
  "path" : null,
  "cocode" : null,
  "licence" : "FREE|PERSONAL|PROFESIONAL|TEAM",
  "factory" : null,
  "cloneOther" : [ 72 ],
  "importData" : [ 71, 72 ],
  "useData" : [ 71, 72 ],
  "useJson" : [ 72 ]
},{
  "props" : null,
  "idxarchitect" : 79,
  "delete" : false,
  "active" : true,
  "clxmlconfig" : null,
  "imagen" : "img/programming/angular.png",
  "icono" : null,
  "txhandlerclass" : "org.enartframework.suinsit.factorys.SimpleFactoryArchitectImpl",
  "txbasepackage" : "com.suinsit.architecture.micros",
  "fxalta" : null,
  "dsdescription" : "Aplicaciones Web Omnicanal con tecnología Angular y backend con micro servicios java springboot",
  "btactive" : false,
  "txname" : "Angular aplicación Low Code",
  "path" : null,
  "cocode" : null,
  "licence" : "FREE|PERSONAL|PROFESIONAL|TEAM",
  "factory" : null,
  "cloneOther" : [ 72 ],
  "importData" : [ 71, 72 ],
  "useData" : [ 71, 72 ],
  "useJson" : [ 72 ]
},{
  "props" : null,
  "idxarchitect" : 80,
  "delete" : false,
  "active" : true,
  "clxmlconfig" : null,
  "imagen" : "img/programming/vuejs.png",
  "icono" : null,
  "txhandlerclass" : "org.enartframework.suinsit.factorys.SimpleFactoryArchitectImpl",
  "txbasepackage" : "com.suinsit.architecture.micros",
  "fxalta" : null,
  "dsdescription" : "Aplicaciones Web Omnicanal con tecnología vuejs y backend con micro servicios java springboot",
  "btactive" : false,
  "txname" : "VueJs aplicación Low Code",
  "path" : null,
  "cocode" : null,
  "licence" : "FREE|PERSONAL|PROFESIONAL|TEAM",
  "factory" : null,
  "cloneOther" : [ 72 ],
  "importData" : [ 71, 72 ],
  "useData" : [ 71, 72 ],
  "useJson" : [ 72 ]
} ,{
  "props" : null,
  "idxarchitect" : 82,
  "delete" : false,
  "active" : true,
  "clxmlconfig" : null,
  "imagen" : "img/programming/Logo_Laravel.png",
  "icono" : null,
  "txhandlerclass" : "org.enartframework.suinsit.factorys.SimpleFactoryArchitectImpl",
  "txbasepackage" : "com.suinsit.architecture.micros",
  "fxalta" : null,
  "dsdescription" : "Aplicaciones Web con tecnología php y framework laravel",
  "btactive" : false,
  "txname" : "Php Laravel aplicación Low Code",
  "path" : null,
  "cocode" : null,
  "licence" : "FREE|PERSONAL|PROFESIONAL|TEAM",
  "factory" : null,
  "cloneOther" : [ 72 ],
  "importData" : [ 71, 72 ],
  "useData" : [ 71, 72 ],
  "useJson" : [ 72 ]
}  ,{
  "props" : null,
  "idxarchitect" : 80,
  "delete" : false,
  "active" : true,
  "clxmlconfig" : null,
  "imagen" : "img/programming/ionic.png",
  "icono" : null,
  "txhandlerclass" : "org.enartframework.suinsit.factorys.SimpleFactoryArchitectImpl",
  "txbasepackage" : "com.suinsit.architecture.micros",
  "fxalta" : null,
  "dsdescription" : "Aplicaciones hibridas (Movil-Web ominical) con framework ionic + angular y micro servicios java springboot",
  "btactive" : false,
  "txname" : "Ionic Web y Apps Low Code",
  "path" : null,
  "cocode" : null,
  "licence" : "FREE|PERSONAL|PROFESIONAL|TEAM",
  "factory" : null,
  "cloneOther" : [ 72 ],
  "importData" : [ 71, 72 ],
  "useData" : [ 71, 72 ],
  "useJson" : [ 72 ]
} ]
