{
  "databases" : [ {
    "defecto" : true,
    "online" : true,
    "updateModel" : false,
    "updateData" : true,
    "createProject" : true,
    "serverFromProject" : false,
    "demo" : true,
    "id" : "2",
    "name" : "H2",
    "url" : "jdbc:h2:tcp://localhost:9095//$ARTFACTOHOME$/database/projects/$PROJECT$$VERSION$",
    "user" : "SA",
    "password" : "",
    "schema" : null,
    "driver" : "org.h2.Driver",
    "classDAO" : null,
    "classMetaModel" : "io.artfacto.mapping.database.database.ddl.h2.datamodel.MetamodelImpl",
    "classServer" : "io.artfacto.mapping.database.database.ddl.h2.ServerImpl",
    "argsServer" : "-tcpPort| 9095|-tcpAllowOthers|-baseDir|$ARTFACTOHOME$/database/projects|-ifNotExists|-tcpDaemon",
    "serverhost" : null,
    "database" : null,
    "port" : 0,
    "fields" : [ ],
    "models" : [ ],
    "mSemanticBean" : { }
  }, {
    "defecto" : false,
    "online" : true,
    "updateModel" : false,
    "updateData" : true,
    "createProject" : true,
    "serverFromProject" : false,
    "demo" : false,
    "id" : "6",
    "name" : "PGSQL",
    "url" : "jdbc:postgresql://$SERVER_IP$:$SERVER_PORT$/$DATABASE$",
    "user" : "suinsit",
    "password" : "spy_230266",
    "schema" : null,
    "driver" : "org.postgresql.Driver",
    "classDAO" : null,
    "classMetaModel" : "io.artfacto.mapping.database.database.ddl.pgsql.datamodel.MetamodelImpl",
    "classServer" : "io.artfacto.mapping.database.database.ddl.h2.ServerImpl",
    "argsServer" : null,
    "serverhost" : "51.91.142.242",
    "database" : "suinsit",
    "port" : 32503,
    "fields" : [ ],
    "models" : [ ],
    "mSemanticBean" : { }
  }],
  "arquitecturas" : [ ]
}
